### PR TITLE
support.transitions for expand/collapse

### PR DESCRIPTION
**Pull request by andhie**
Thanks to @nickbutcher for the trick

### CODE REVIEW

**Comment by nickbutcher** [comment]
Nice! You might also consider using a payload when calling `onItemChanged`, this way you can only update the changed `Views` and not have to re-bind untouched parts. 

See:
https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/DribbbleShot.java#L975
https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/DribbbleShot.java#L1150

**Comment by andhie** [comment]
I'm aware of the payload version. since the only things that rebind are 2 `TextView` and `CardView` background color. That would be minor enhancement compared to other stuffs that are hacked together. 

Yet its still a far cry from @taylorling vision of the app which i have no idea how to implement the text expansion anim (specifically when the Location name text becomes multi-line on expand)
https://dribbble.com/shots/2243862-Haze-Watch-2-0-Concept-Revision

**Comment by nickbutcher** [comment]
You can use Plaid's [ReflowText transition](https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/transitions/ReflowText.java).

**Comment by andhie** [comment]
Thank you for the hint. I'll check it out.

Note: When click (expand Animation will occurs), quickly scroll the `RecyclerView` will crash. Need to revert or a fix before next update.

``` java
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    at android.view.ViewGroup.addViewInner(ViewGroup.java:4309)
    at android.view.ViewGroup.addView(ViewGroup.java:4145)
    at android.view.ViewGroup.addView(ViewGroup.java:4086)
    at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:649)
    at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
    at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7112)
    at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7070)
    at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7058)
    at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:564)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
    at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1193)
    at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1043)
    at android.support.v7.widget.GridLayoutManager.scrollVerticallyBy(GridLayoutManager.java:381)
    at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1596)
    at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2704)
    at android.view.View.dispatchTouchEvent(View.java:9300)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
    at android.view.View.dispatchPointerEvent(View.java:9520)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
    at android.view.ViewRootImpl$Input
```

**Comment by nickbutcher** [comment]
I encountered a different [issue](https://github.com/nickbutcher/plaid/issues/92) with scrolling the RV while the transition is running. I opted to [ignore touch events](https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/DribbbleShot.java#L455) for the (brief) duration of the transition.

**Comment by andhie** [comment]
Implemented the same approach. Trying to scroll during animation, will not crash it, but after `onTransitionEnd`, `RecyclerView` will just 'jump' as if its trying to make up the intercepted scroll.

Although i feel using `RecyclerView#ItemAnimator` would be more appropriate but at the cost of more code.

Thanks a lot for your insights. and the support library team for back porting Transitions

**Pull request merged**
